spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/productdb_prod  # to be changed with a real IP for live connection
    username: prod_user
    password: prod_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate  # prod data control by hand?
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: e_commerce

server:
  port: 80  # live port

logging:
  level:
    root: INFO
